apiVersion: v1
kind: Service
metadata:
 name: dakshesh-apache2-service
 namespace: dakshesh
spec:
 type: NodePort
 ports:
   - port: 81
     targetPort: 81
     nodePort: 30015
 selector:
   file: apache2
